// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjbszgwhlgcrctkqghpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqYnN6Z3dobGdjcmN0a3FnaHBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NTQ5MTYsImV4cCI6MjA3MzQzMDkxNn0.hHvsgSdzu18HzUVlIU6ZSEoADvc2zxRNWykfBAd1Qkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});